#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2019.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2020.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2021.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vpd_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/vs_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/th_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/erc_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm100_2022.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/fm1000_2022.nc

